const CACHE='freelancekit-v3.1.1';
const CORE=[
 './index.html',
 './about.html',
 './privacy.html',
 './terms.html',
 './style.css',
 './app.js',
 './site-config.js',
 './manifest.webmanifest',
 './robots.txt',
 './assets/favicon.svg',
 './data/currencies.js',
 './data/tools.js',
 './data/tool-fields.js',
 './data/locales/de.js',
 './data/locales/en.js',
 './data/locales/es.js',
 './data/locales/fr.js',
 './data/locales/it.js',
 './data/locales/pl.js',
 './data/locales/pt.js',
 './data/locales/ru.js',
 './tools/annual-income-calculator/index.html',
 './tools/billable-hours-calculator/index.html',
 './tools/break-even-calculator/index.html',
 './tools/business-days-calculator/index.html',
 './tools/cash-flow-calculator/index.html',
 './tools/client-lifetime-value-calculator/index.html',
 './tools/client-onboarding-generator/index.html',
 './tools/cost-plus-pricing-calculator/index.html',
 './tools/currency-converter/index.html',
 './tools/day-rate-calculator/index.html',
 './tools/deadline-calculator/index.html',
 './tools/deposit-calculator/index.html',
 './tools/discount-calculator/index.html',
 './tools/effective-hourly-rate/index.html',
 './tools/follow-up-email-generator/index.html',
 './tools/hourly-rate-calculator/index.html',
 './tools/index.html',
 './tools/invoice-generator/index.html',
 './tools/installment-calculator/index.html',
 './tools/invoice-description-generator/index.html',
 './tools/invoice-total-calculator/index.html',
 './tools/late-fee-calculator/index.html',
 './tools/late-payment-email-generator/index.html',
 './tools/markup-calculator/index.html',
 './tools/meeting-agenda-generator/index.html',
 './tools/monthly-income-calculator/index.html',
 './tools/overtime-rate-calculator/index.html',
 './tools/payment-fee-calculator/index.html',
 './tools/profit-margin-calculator/index.html',
 './tools/project-buffer-calculator/index.html',
 './tools/project-price-calculator/index.html',
 './tools/project-scope-generator/index.html',
 './tools/proposal-generator/index.html',
 './tools/quote-total-calculator/index.html',
 './tools/rate-increase-email-generator/index.html',
 './tools/retainer-price-calculator/index.html',
 './tools/revenue-target-calculator/index.html',
 './tools/roi-calculator/index.html',
 './tools/runway-calculator/index.html',
 './tools/savings-goal-calculator/index.html',
 './tools/service-package-generator/index.html',
 './tools/tax-estimate-calculator/index.html',
 './tools/testimonial-request-generator/index.html',
 './tools/time-zone-converter/index.html',
 './tools/utilization-calculator/index.html',
 './tools/vacation-rate-calculator/index.html',
 './tools/working-hours-calculator/index.html'
];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{
 const u=new URL(e.request.url);
 if(e.request.method!=='GET'||u.origin!==location.origin)return;
 // Never intercept top-level document navigations. Cloudflare Pages may normalize
 // /tools/foo/index.html -> /tools/foo/; returning redirects from a service
 // worker breaks Safari/WebKit navigation. Let the browser follow redirects.
 if(e.request.mode==='navigate' || e.request.destination==='document') return;
 e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r;}).catch(()=>caches.match(u.href))));
});
